query GetArticle($id: Float!) {
  article(id: $id) {
    id
    title
    body
    mainPictureUrl
    createdAt
    updatedAt
    category {
      name
    }
  }
}

query GetLatestArticles($limit: Float) {
  articles(limit: $limit) {
    id
    title
    mainPictureUrl
  }
}

mutation DeleteArticle($id: Float!) {
  deleteArticle(id: $id)
}

query GetCategories {
  categories {
    id
    name
  }
}

mutation CreateArticle($data: CreateArticleInput!) {
  createArticle(data: $data) {
    id
  }
}
